export enum MaterialIcon {
  Home = "home",
  Delete = "delete",
  Edit = "edit",
  EditSquare = "edit_square",
  Pin = "push_pin",
  Star = "star",
  Add = "add",
  Close = "close",
  Save = "save",
  Logout = "logout",
  Login = "login",
  AddUser = "person_add",
  Boards = "grid_view",
  Board = "assignment",
  Cancel = "cancel",
  Error = "error",
  Group = "group",
  Calendar = "calendar_month",
  None = "none",
}
